In [1]:
import numpy as np

import keras 
from keras.preprocessing.image import ImageDataGenerator

In [2]:
model_path1 = './dataset/horse_or_human_predictor.h5' #new model.ipynb
model_path2 = './dataset/horse_human_cnn_model_v2_1.h5' #v2 solve overfitting Horse_or_human Classification using CNN.ipynb

model1 = keras.models.load_model(model_path1)
model2 = keras.models.load_model(model_path2)

In [3]:
#horse image path
h1 = './dataset/test/horses/hrf1.jfif'
h2 = './dataset/test/horses/hrf2.jfif'
h3 = './dataset/test/horses/hrf3.jfif'

#human image path
hu1 = './dataset/test/humans/hu1.jpg'
hu2 = './dataset/test/humans/hu2 (2).jpg'
hu3 = './dataset/test/humans/hu3.jpg'

In [4]:
import numpy as np
from keras.preprocessing import image


def pred_human_horse(model, horse_or_human):
  test_image = image.load_img(horse_or_human, target_size = (150, 150))
  test_image = image.img_to_array(test_image)/255
  test_image = np.expand_dims(test_image, axis = 0)
 
  result = model.predict(test_image).round(3)
 
  pred = np.argmax(result)
  print(result, "--->>>", pred)
 
  if pred == 0:
    print('Predicted>>> Horse')
  else:
    print('Predicted>>> Human')

In [5]:
for horse_or_human in [h1,h2,h3, hu1,hu2,hu3]:
    pred_human_horse(model1, horse_or_human)



[[0.997 0.003]] --->>> 0
Predicted>>> Horse
[[0. 1.]] --->>> 1
Predicted>>> Human
[[0.384 0.616]] --->>> 1
Predicted>>> Human
[[0.991 0.009]] --->>> 0
Predicted>>> Horse
[[0.001 0.999]] --->>> 1
Predicted>>> Human
[[0.698 0.302]] --->>> 0
Predicted>>> Horse


In [6]:
for horse_or_human in [h1,h2,h3, hu1,hu2,hu3]:
    pred_human_horse(model2, horse_or_human)

[[1. 0.]] --->>> 0
Predicted>>> Horse
[[0.981 0.019]] --->>> 0
Predicted>>> Horse
[[0.559 0.441]] --->>> 0
Predicted>>> Horse
[[0.009 0.991]] --->>> 1
Predicted>>> Human
[[0. 1.]] --->>> 1
Predicted>>> Human
[[0.001 0.999]] --->>> 1
Predicted>>> Human
